import os
from texts.storage import Storage, AuthorName, Book, Content, _Subchapter, _Chapter
storage = Storage(os.path.join(os.getcwd(), 'TEST_TEXTS_DB'))
book = Book('sha2', AuthorName('maran'))
# print(book)
content = storage.get_book_content(book)
# print(content)
print(content.chapters)
# print(content.chapters[0].subchapters)
result = Content()
c = _Chapter('92')
c.add_subchapter(_Subchapter('1', 'seif'))
c.add_subchapter(_Subchapter('2', 'seif'))
c.add_subchapter(_Subchapter('3', 'seif'))
c.add_subchapter(_Subchapter('4', 'seif'))
c.add_subchapter(_Subchapter('5', 'seif'))
c.add_subchapter(_Subchapter('6', 'seif'))
result.add_chapter(c)
c = _Chapter('106')
c.add_subchapter(_Subchapter('1', 'seif'))
result.add_chapter(c)
print(result.chapters)
result.chapters.sort()
content.chapters.sort()
print(result.chapters)
print(content.chapters)